# config/vlp16_test.param.yaml
/**:
  ros__parameters:
    ip: "10.31.32.93"
    port: 8301
    cloud_size:  55000
    topic: "points_raw"  # UdpDriverNode strictly expects to get the topic via `declare_parameter`.
    frame_id: "lidar_rear"
    timeout_ms: 10
    rpm:        600
