/**:
  ros__parameters:
    # Default variance for position and velocity variables in the filters
    ekf_default_variance: 1.0
    # Variance for the noise model in the filters
    ekf_noise_variance: 3.0
    # Gate parameter: Objects farther apart than this distance are not matched.
    association_max_distance: 5.0
    # Gate parameter: Objects whose size differs by more than this factor are not matched.
    association_max_area_ratio: 20.0
    # When true, the shortest edge of the detection will be used as the max distance threshold if it is greater than the configured threshold
    association_consider_edge_for_big_detection: True
    # Time after which to remove unseen tracks.
    # Note also the pruning_ticks_threshold – only one threshold is necessary for removal.
    pruning_time_threshold_ms: 500
    # Number of observations to remove unseen tracks.
    # Note also the pruning_time_threshold_ms – only one threshold is necessary for removal.
    pruning_ticks_threshold: 10
    # Frame id in which tracks should be produced
    track_frame_id: 'odom'