---
/**:
  ros__parameters:
    topics:
      input_pose:
        - /localization/ndt_pose_with_covariance
    data_driven: true
    frame_id: "map"
    mahalanobis_threshold: 1.0

    process_noise_variances:
      acceleration: [2.0, 2.0]

    state_variances: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
