/**:
  ros__parameters:
    enable_object_collision_estimator: true
    heading_weight: 0.1
    goal_distance_thresh: 3.0
    stop_velocity_thresh: 2.0
    subroute_goal_offset_lane2parking: 7.6669
    subroute_goal_offset_parking2lane: 7.6669
    vehicle:
      cg_to_front_m: 1.228
      cg_to_rear_m: 1.5618
      front_corner_stiffness: 17000.0  # NOT USED
      rear_corner_stiffness: 20000.0   # NOT USED
      mass_kg: 1460.0                  # NOT USED
      yaw_inertia_kgm2: 2170.0         # NOT USED
      width_m: 2.0                     # NOT USED
      front_overhang_m: 0.5
      rear_overhang_m: 0.5