#!/usr/bin/env bash

apm install \
    atom-beautify \
    atom-ide-ui \
    atom-ide-debugger-native-gdb \
    atom-ide-debugger-python \
    autocomplete-clang \
    build \
    build-colcon \
    busy-signal \
    highlight-selected \
    ide-python \
    intentions \
    language-cmake \
    language-docker \
    linter \
    linter-docker \
    linter-shellcheck \
    linter-ui-default \
    minimap \
    minimap-highlight-selected \
    minimap-split-diff \
    platformio-ide-terminal \
    pretty-json \
    split-diff


if [[ ! -f ~/.atom/config.cson ]]; then
    cat > ~/.atom/config.cson <<-EOF
	"*":
	  "atom-beautify":
	    c:
	      configPath: "/opt/ros/dashing/lib/python3.6/site-packages/ament_uncrustify/configuration/ament_code_style.cfg"
	    cpp:
	      configPath: "/opt/ros/dashing/lib/python3.6/site-packages/ament_uncrustify/configuration/ament_code_style.cfg"
	  core:
	    disabledPackages: [
	      "linter"
	    ]
	  "ide-python":
	    python: "python3"
	EOF
fi


if [[ ! -f ~/.atom/keymap.cson ]]; then
    cat > ~/.atom/keymap.cson <<-EOF
	'atom-workspace':
	  'f6': 'autocomplete-clang:go-declaration'
	'.platform-linux atom-text-editor':
	  'ctrl-space': 'symbols-view:go-to-declaration'
	  'ctrl-shift-space': 'symbols-view:return-from-declaration'
	'atom-text-editor':
	  'ctrl-alt-u': 'atom-beautify:beautify-editor'
	EOF
fi
