# config/state_estimator_test.param.yaml
---

/**:
  ros__parameters:
    topics:
      input_odom:
        - /odom_topic_1
        - /odom_topic_2
      input_pose:
        - /pose_topic_1
        - /pose_topic_2
      input_twist:
        - /twist_topic_1
        - /twist_topic_2
    data_driven: true
    frame_id: "map"
    mahalanobis_threshold: 10.0
    state_variances: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    process_noise_variances:
      acceleration: [1.0, 1.0]
