name: Test
on:
  pull_request
env:
  CARGO_TERM_COLOR: always
jobs:
  doc:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: env
    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: foxy
    - name: Build Autoware.Auto
      continue-on-error: true
      run: |
        cmake --version
        apt-get update && apt-get -y --no-install-recommends install \
          build-essential \
          clang-tidy \
          cmake \
          python3-colcon-common-extensions \
          python3-rosdep \
          python3-vcstool \
          ros-foxy-cyclonedds \
          ros-foxy-rmw-cyclonedds-cpp
        vcs import < autoware.auto.foxy.repos
        rosdep update
        rosdep install -y --from . --ignore-src --rosdistro foxy
        curl https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/raw/master/src/launch/autoware_demos/data/autonomoustuff_parking_lot_lgsvl.pcd -o src/launch/autoware_demos/data/autonomoustuff_parking_lot_lgsvl.pcd
        source /opt/ros/foxy/setup.bash
        colcon build --merge-install --packages-up-to benchmark_tool_nodes
    - uses: actions/upload-artifact@v2
      with:
        name: build-dir
        path: build
